Issue 857 - Chart loading skeleton
hackoregon/civic pull request #858
Opened 2019-08-28 09:35 UTC by jaronheard

Resolves #857.

This adds a loading skeleton to charts.

Prior to this PR, charts did not have a height before they were loaded, so it caused a page reflow.

| Before  | After |
| ------------- | ------------- |
| ![Screen Recording 2019-08-28 at 2 25 55 AM](https://user-images.githubusercontent.com/7065695/63843581-7124c780-c93b-11e9-9b32-849e2fcfe543.gif)  | ![Screen Recording 2019-08-28 at 2 22 22 AM](https://user-images.githubusercontent.com/7065695/63843582-7124c780-c93b-11e9-8503-abc638588574.gif)  |
 
That said, there's a number of things on this PR that I'm not especially confident in.

- This adds a dependency on @material-ui/labs, as the Skeleton component is not yet in the @material-ui/core. Rather than add a dependency, should we just implement this as an individual component?
- Should the Skeleton be its own component? Or is it ok to just have it be implemented in ChartWrapper?
- I added a check for `safeData` to avoid having the charts throw errors if `data` is null and `isLoading` is true, but it smells fishy to me.

2019-08-29 05:46 UTC, ghost requested changes

2019-08-29 06:11 UTC, Dianna commented
We should have the `isLoading` prop in all visualizations so we don't have to do the conditional chart mount which causes a layout jump. If that's done here, I'll update the cards in #873 to use it, otherwise if mine is merged first we'll need to do a sweep later and update them.

2019-08-31 04:20 UTC, Dianna commented
Height ratio is off. Also, to keep this user friendly we should show the user _something_ besides just a grayish rectangle.

2019-09-06 10:06 UTC, jaronheard commented
Current status for this PR:

- It adds a skeleton with the proper height to ChartContainer.
- It resolves #914 

It adds a note about a newly discovered issue with LineChart, which will be covered in another PR:
If there are lines that have different numbers of data points, then they will be colored incorrectly.

2019-09-07 03:40 UTC, ghost approved these changes
Loading "skeleton" ratio now works and has a spinner to indicate somethings happening. Tests and documentation look good for protectData

2019-09-07 04:55 UTC, merged